@startuml
hide circle
skinparam classBackgroundColor #Business
skinparam linetype ortho
skinparam Shadowing True
skinparam TitleFontSize 72pt

title Horizon Research Project (HRP) \n Evaluation Schema Diagram \n Version 26.5.16

entity "Basic.DocumentType" as documentType #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.FileExtension" as fileExtension #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.Document" as document #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TableName : varchar(255)
  *TableId : bigint(19)
  *DocumentTypeId : uui <<FK>>
  *FileExtensionId : uui <<FK>>
  *FileAddress: varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.ProjectWorkflowDocumentType" as projectWorkflowDocumentType #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *DocumentTypeId : uui <<FK>> <<composite unique>>
  *ProjectWorkflowId : uui <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.WorkflowEligibleFileExtension" as workflowEligibleFileExtension #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *WorkflowId : uui <<FK>> <<composite unique>>
  *FileExtensionId : uui <<FK>> <<composite unique>>
  *MaxFileSizeForUpload : integer <<default: 5242880>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

documentType ||..o{ document
fileExtension ||..o{ document

@enduml