@startuml
hide circle
skinparam classBackgroundColor #Business
skinparam linetype ortho
skinparam Shadowing True
skinparam TitleFontSize 72pt

title Horizon Research Project (HRP) \n Evaluation Schema Diagram \n Version 26.5.18

entity "UserManagement.Profile" as profile #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *FirstName : varchar(200)
  *LastName : varchar(200)
  *Gender : enum(male, female)
  *StaffNumber : varchar(20) <<unique>>
  *ActiveFrom : timestamp
  ActiveTo : timestamp
  PositionId : uui <<FK>>
  Avatar : text
  Birthday : date
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  EmailAddress : varchar(200)
  Address : varchar(1000)
  PostalCode : varchar(20)
  LastLogInDate : timestamp
  LogInCount : integer(10) <<default: 0>>
  WrongLogInCount : integer(10) <<default: 0>>
  *Username : varchar(200) <<unique>>
  *Pass : varchar(255)
  PassSalt : varchar(50)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Department" as department #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(50)
  *Code : varchar(20) <<unique>>
  ParentId : integer(20) <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Project" as project #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  StartDate : date
  EndDate : date
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.Customer" as customer #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(255)
  Description : varchar(4000)
  Address : varchar(4000)
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  Email : varchar(100)
  PostalCode : varchar(20)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.Question" as question #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireId : uui <<FK>>
  *Question : varchar(4000)
  *Code : varchar(20) <<unique>>
  *AnswerType : enum(SingleChoice, MultiChoice, Description)
  *Score : integer
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionOption" as questionOption #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionId : uui <<FK>>
  *Title : varchar(4000)
  *Score : integer
  *IsDescriptionRequired : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.Questionnaire" as questionnaire #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  ProjectId : uui <<FK>>
  *QuestionnaireAduience : enum(Staffs, Customers, SeniorManagers, Stackholders)
  *TotalScore : integer
  *AcceptableScore : integer
  *WarningScore : integer
  *DisasterScore : integer
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionnaireTargetDepartment" as questionnaireTargetDepartment #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireId : uui <<FK>>
  *DepoartmentId : uui <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionnaireItem" as questionnaireItem #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireId : uui <<FK>>
  *QuestionId : uui <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionnaireResult" as questionnaireResult #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireId : uui <<FK>>
  ProfileId : uui <<FK>>
  CustomerId : uui <<FK>>
  *TotalScore : integer
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionnaireResultDetail" as questionnaireResultDetail #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireResultId : uui <<FK>>
  *QuestionnaireItemId : uui <<FK>>
  ChoosedQuestionOptionId : uui <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.CustomerFeedback" as customerFeedback #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CustomerId : uui <<FK>>
  *ProjectId : uui <<FK>>
  *FeedbackDate : date
  *FeedbackValue : numeric(2,2) <<between 1 and 10>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.StaffSatisfactionEvaluation" as staffSatisfactionEvaluation #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uui <<FK>>
  *EvalationDate : date
  *EvaluatedValue : numeric(3,2) <<between 1 and 100>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.ProjectProductivityEvaluation" as projectProductivityEvaluation #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  *EvalationDate : datetime
  *EvaluatedValue : numeric(3,2) <<between 1 and 100>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.CustomerSatisfactionEvaluation" as customerSatisfactionEvaluation #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CustomerId : uui <<FK>>
  *ProjectId : uui <<FK>>
  *EvalationDate : datetime
  *EvaluatedValue : numeric(3,2) <<between 1 and 100>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

questionnaire ||..o{ questionnaireTargetDepartment
department ||..o{ questionnaireTargetDepartment
question ||..o{ questionnaireItem
project ||..o{ questionnaire
questionnaire ||..o{ questionnaireItem
question ||..o{ questionOption
questionnaire ||..o{ questionnaireResult
profile |o..o{ questionnaireResult
customer |o..o{ questionnaireResult
questionnaireResult ||..o{ questionnaireResultDetail
questionnaireItem ||..o{ questionnaireResultDetail
questionOption |o..o{ questionnaireResultDetail
profile ||..o{ staffSatisfactionEvaluation
project ||..o{ projectProductivityEvaluation
customer ||..o{ customerSatisfactionEvaluation
project ||..o{ customerSatisfactionEvaluation
customer ||..o{ customerFeedback
project ||..o{ customerFeedback

@enduml