@startuml
hide circle
skinparam classBackgroundColor #Business
skinparam linetype ortho
skinparam Shadowing True
skinparam TitleFontSize 72pt

title Horizon Research Project (HRP) \n Quality Control Schema Diagram \n Version 26.6.13

entity "Basic.TestApproval" as testApproval #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *IsApproved : boolean
  *Color : varchar(10)
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.TestComplexityLevel" as testComplexityLevel #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *ValueNumber : float
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Project" as project #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  StartDate : date
  EndDate : date
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectRelease" as release #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  *VersionNumber : varchar(20) <<unique>>
  ReleaseDate : date
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Issue" as issue #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  AssigneeId : uui <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  DueDate : date
  PriorityId : uui <<FK>>
  *IssueTypeId : uui <<FK>>
  *CuurentStatusId : uui <<FK>>
  *CurrentResolvationId : uui <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestScenario" as testScenario #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(255)
  TestComplexityLevelId : uui <<FK>>
  UsersAndRoles : varchar(4000)
  Steps : varchar(4000)
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.PrerequisiteTestScenario" as prerequisiteTestScenario #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TestScenarioId : uui <<FK>>
  *PrerequisiteTestScenarioId : uui <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestPlan" as testPlan #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Code : varchar(20) <<unique>>
  *Title : varchar(255)
  PlanningDate : date
  ProjectReleaseId : uui <<FK>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestPlanScenario" as testPlanScenario #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TestScenarioId : uui <<FK>> <<composite unique>>
  *TestPlanId : uui <<FK>> <<composite unique>>
  *Ordering : float <<composite unique>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestPlanScenarioIssueCoverage" as testPlanScenarioIssueCoverage #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TestPlanScenarioId : uui <<FK>> <<composite unique>>
  *IssueId : uui <<FK>> <<composite unique>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestResult" as testResult #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TestDate : date
  *TestPlanId : uui <<FK>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestResultDetail" as testResultDetail #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  TestPlanScenarioId : uui <<FK>>
  *TestApprovalId : uui <<FK>>
  *Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

project ||..o{ release
project ||..o{ testScenario
testComplexityLevel |o..o{ testScenario
testScenario ||..o{ prerequisiteTestScenario
testScenario ||..o{ prerequisiteTestScenario
testScenario ||..o{ prerequisiteTestScenario
release |o..o{ testPlan
testScenario ||..o{ testPlanScenario
testPlan ||..o{ testPlanScenario
testPlanScenario ||..o{ testPlanScenarioIssueCoverage
issue ||..o{ testPlanScenarioIssueCoverage
testPlan ||..o{ testResult
testPlanScenario |o..o{ testResultDetail
testApproval ||..o{ testResultDetail

@enduml