@startuml
hide circle
skinparam classBackgroundColor #Business
skinparam linetype ortho
skinparam Shadowing True
skinparam TitleFontSize 72pt

title Horizon Research Project (HRP) \n Finance Schema Diagram \n Version 26.5.16

entity "Basic.ContractType" as contractType #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.Currency" as currency #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *Symbol : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.TimeUnit" as timeUnit #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  BasedOnMillisecond : bigint(19)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Project" as project #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  StartDate : date
  EndDate : date
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectRelease" as release #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  *VersionNumber : varchar(20) <<unique>>
  ReleaseDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.Document" as document #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TableName : varchar(255)
  *TableId : bigint(19)
  *DocumentTypeId : uui <<FK>>
  *FileExtensionId : uui <<FK>>
  *FileAddress: varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Profile" as profile #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *FirstName : varchar(200)
  *LastName : varchar(200)
  *Gender : enum(male, female)
  *StaffNumber : varchar(20) <<unique>>
  *ActiveFrom : timestamp
  ActiveTo : timestamp
  PositionId : uui <<FK>>
  Avatar : text
  Birthday : date
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  EmailAddress : varchar(200)
  Address : varchar(1000)
  PostalCode : varchar(20)
  LastLogInDate : timestamp
  LogInCount : integer(10) <<default: 0>>
  WrongLogInCount : integer(10) <<default: 0>>
  *Username : varchar(200) <<unique>>
  *Pass : varchar(255)
  PassSalt : varchar(50)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.StaffContract" as staffContract #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uui <<FK>>
  *ContractTypeId : uui <<FK>>
  *StartDate : date
  *EndDate : date
  *Title : varchar(200)
  Description : varchar(4000)
  AutoRenewal : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractSalaryItem" as contractSalaryItem #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *StaffContractId : uui <<FK>>
  *Title : varchar(200)
  *Amount : numeric(22,2)
  *CurrencyId : uui <<FK>>
  Description : varchar(4000)
  *CalculationTimeUnitId : uui <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractDeductionItem" as contractDeductionItem #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *StaffContractId : uui <<FK>>
  *Title : varchar(200)
  *CalculationType : enum(percentage, fixedAmount)
  DeductionPercentage : numeric(3,2) <<from 0 until 100>>
  FixedAmount : numeric(22,2)
  FixedAmountCurrencyId : uui <<FK>>
  Description : varchar(4000)
  *CalculationTimeUnitId : uui <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.Supplier" as supplier #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(255)
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  FaxNumber : varchar(20)
  Email : varchar(100)
  PostalCode : varchar(20)
  City : varchar(255)
  Address : varchar(4000)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.CostInvoice" as costInvoice #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *SupplierId : uui <<FK>>
  *DocumentId : uui <<FK>>
  *InvoiceDate : date
  *TotalAmount : numeric(22,2)
  *CurrencyId : uui <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.CostInvoiceItem" as costInvoiceItem #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CostInvoiceId : uui <<FK>>
  *ItemTitle : varchar(255)
  *UnitAmount : numeric(22,2)
  *CurrencyId : uui <<FK>>
  *Quantity : float
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ProjectDirectCostItem" as projectDirectCostItem #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  *CostInvoiceItemId : uui <<FK>>
  *AllocatedQuantity : float
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.CostPaymentReceipt" as costPaymentReceipt #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CostInvoiceId : uui <<FK>>
  *ReceiptNumber : varchar(20)
  *DocumentId : uui <<FK>>
  *Amount : numeric(22,2)
  *CurrencyId : uui <<FK>>
  *PaymentDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.SalaryPaymentReceipt" as salaryPaymentReceipt #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *StaffContractId : uui <<FK>>
  *ReceiptNumber : varchar(20)
  *DocumentId : uui <<FK>>
  *Amount : numeric(22,2)
  *CurrencyId : uui <<FK>>
  *PaymentDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.StaffAdditionalPaymentReceipt" as staffAdditionalPaymentReceipt #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uui <<FK>>
  *Title : varchar(255)
  *DocumentId : uui <<FK>>
  *Amount : numeric(22,2)
  *CurrencyId : uui <<FK>>
  *PaymentDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.Customer" as customer #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(255)
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  Email : varchar(100)
  PostalCode : varchar(20)
  Address : varchar(4000)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.Contract" as contract #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CustomerId : uui <<FK>>
  *ProjectId : uui <<FK>>
  *ContractNumber : varchar(20)
  StartDate : date
  ScheduledEndDate : date
  RealEndDate : date
  IsDevelopmentContract : boolean
  IsSupportContract : boolean
  *TotalAmount : numeric(22,2)
  *CurrencyId : uui <<FK>>
  DocumentId : uui <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractPaymentSchedule" as contractPaymentSchedule #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ContractId : uui <<FK>>
  *PaymentTitle : varchar(255)
  ProjectReleaseId : uui <<FK>>
  ScheduledPaymentDate : date
  *Amount : numeric(22,2)
  *CurrencyId : uui <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractPaymentReceipt" as contractPaymentReceipt #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ContractPaymentScheduleId : uui <<FK>>
  *ReceiptNumber : varchar(20)
  *PaymentDate : date
  DocumentId : uui <<FK>>
  *Amount : numeric(22,2)
  *CurrencyId : uui <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}



contractType ||..o{ staffContract
profile ||..o{ staffContract
staffContract ||..o{ contractSalaryItem
timeUnit ||..o{ contractSalaryItem
currency ||..o{ contractSalaryItem
supplier ||..o{ costInvoice
document ||..o{ costInvoice
currency ||..o{ costInvoice
costInvoice ||..o{ costInvoiceItem
currency ||..o{ costInvoiceItem
costInvoiceItem ||..o{ projectDirectCostItem
project ||..o{ projectDirectCostItem
costInvoiceItem ||..o{ projectDirectCostItem
costInvoice ||..o{ costPaymentReceipt
document ||..o{ costPaymentReceipt
currency ||..o{ costPaymentReceipt
staffContract ||..o{ contractDeductionItem
timeUnit ||..o{ contractDeductionItem
currency ||..o{ contractDeductionItem
document ||..o{ salaryPaymentReceipt
staffContract ||..o{ salaryPaymentReceipt
currency ||..o{ salaryPaymentReceipt
profile ||..o{ staffAdditionalPaymentReceipt
document ||..o{ staffAdditionalPaymentReceipt
contract ||..o{ contractPaymentSchedule
currency ||..o{ contractPaymentSchedule
release ||..o{ contractPaymentSchedule
contractPaymentSchedule ||..o{ contractPaymentReceipt
currency ||..o{ contractPaymentReceipt
document ||..o{ contractPaymentReceipt
customer ||..o{ contract
project ||..o{ contract
currency ||..o{ contract
document |o..o{ contract

@enduml