@startuml
hide circle
skinparam classBackgroundColor #Business
skinparam linetype ortho
skinparam Shadowing True
skinparam TitleFontSize 72pt

title Horizon Research Project (HRP) \n Project Management Schema Diagram \n Version 26.6.13

entity "Basic.Priority" as priority #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *Ordering : integer
  *Color : varchar(7)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.IssueType" as issueType #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *IconAddress : varchar(1000)
  *Color : varchar(7)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.Status" as status #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *Color : varchar(7)
  *StatusEffect : enum(ToDo, InProgress, Done)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.Resolvation" as resolvation #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *Color : varchar(7)
  *IsResolved : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.MeetingType" as meetingType #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.TimeUnit" as timeUnit #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  BasedOnMillisecond : bigint(19)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.Document" as document #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TableName : varchar(255)
  *TableId : bigint(19)
  *DocumentTypeId : uui <<FK>>
  *FileExtensionId : uui <<FK>>
  *FileAddress: varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Role" as role #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Groups" as groups #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Profile" as profile #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *FirstName : varchar(200)
  *LastName : varchar(200)
  *Gender : enum(male, female)
  *StaffNumber : varchar(20) <<unique>>
  *ActiveFrom : timestamp
  ActiveTo : timestamp
  PositionId : uui <<FK>>
  Avatar : text
  Birthday : date
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  EmailAddress : varchar(200)
  Address : varchar(1000)
  PostalCode : varchar(20)
  LastLogInDate : timestamp
  LogInCount : integer(10) <<default: 0>>
  WrongLogInCount : integer(10) <<default: 0>>
  *Username : varchar(200) <<unique>>
  *Pass : varchar(255)
  PassSalt : varchar(50)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.ProjectWorkflowDocumentType" as projectWorkflowDocumentType #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *DocumentTypeId : uui <<FK>> <<composite unique>>
  *ProjectWorkflowId : uui <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Department" as department #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(50)
  *Code : varchar(20) <<unique>>
  ParentId : integer(20) <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Project" as project #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  StartDate : date
  EndDate : date
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectProfileMember" as projectProfileMember #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>> <<composite unique>>
  *ProfileId : uui <<FK>> <<composite unique>>
  *IsProjectManager : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectGroupMember" as projectGroupMember #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>> <<composite unique>>
  *GroupId : uui <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectRoleMember" as projectRoleMember #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>> <<composite unique>>
  *RoleId : uui <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectDepartmentMember" as projectDepartmentMember #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>> <<composite unique>>
  *DepartmentId : uui <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflow" as projectWorkflow #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflowStatus" as projectWorkflowStatus #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectWorkflowId : uui <<FK>>
  *StatusId : uui <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflowResolvation" as projectWorkflowResolvation #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectWorkflowId : uui <<FK>>
  *ResolvationId : uui <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflowProgress" as projectWorkflowProgress #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(255)
  StartProjectWorkflowStatusId : uui <<FK>>
  *IsFromStartPoint : boolean
  *CanBeStartedFromAnyStatus : boolean
  EndProjectWorkflowStatusId : uui <<FK>>
  *IsWorkflowEndPoint : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Issue" as issue #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  AssigneeId : uui <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  DueDate : date
  PriorityId : uui <<FK>>
  *IssueTypeId : uui <<FK>>
  IssueSize : enum(XS, S, M , L , XL)
  ParentIssueId : uui <<FK>>
	EpicLinkedId : uui <<FK>>
	LinkedIssueId : uui <<FK>>
	LinkedIssueType : enum(Blocks, RelatesTo, Duplicates, Clones)
  *CurrentStatusId : uui <<FK>>
  *CurrentResolvationId : uui <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.IssueComment" as issueComment #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *IssueId : uui <<FK>>
  *CommentText : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.IssueAttachment" as issueAttachment #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *IssueId : uui <<FK>> <<composite unique>>
  *DocumentId : uui <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectRelease" as release #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  *VersionNumber : varchar(20) <<unique>>
  ReleaseDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectReleaseIssue" as releaseIssue #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectReleaseId : uui <<FK>> <<composite unique>>
  *IssueId : uui <<FK>> <<composite unique>>
  IsFinalized : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.WorkLog" as workLog #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *IssueId : uui <<FK>>
  *LogDate : date
  *StartWorkTime : time
  *WorkingDuration : float 
  *TimeUnitId : uui <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.WorkflowEligibleFileExtension" as workflowEligibleFileExtension #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *WorkflowId : uui <<FK>> <<composite unique>>
  *FileExtensionId : uui <<FK>> <<composite unique>>
  *MaxFileSizeForUpload : integer <<default: 5242880>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.IssueWorkflowHistory" as issueWorkflowHistory #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *IssueId : uui <<FK>>
  *StartStatusId : uui <<FK>>
  *EndStatusId : uui <<FK>>
  *ProjectWorkflowProgressId : uui <<FK>>
  ProjectWorkflowResolvationId : uui <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectMeeting" as projectMeeting #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uui <<FK>>
  *MeetingTypeId : uui <<FK>>
  *MeetingDate : date
  *Title : varchar(255)
  *Location : varchar(255)
  MinutesDocumentId : uui <<FK>>
  Description : varchar(4000)
  ScheduleStartTime : time
  ScheduleEndTime : time
  ActualStartTime : time
  ActualEndTime : time
  *IsCanncelled : boolean <<default: false>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.MeetingInvitees" as meetingInvitees #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectMeetingId : uui <<FK>>
  *IsFromInsideCompnay : boolean
  ProfileId : uui <<FK>>
  InviteeFullName : varchar(255)
	InviteeCompanyName : varchar(255)
  IsAttanded : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.MeetingMinutes" as meetingMinutes #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectMeetingId : uui <<FK>>
  *Resolution : varchar(4000)
  ResponsibleDepartmentId : uui <<FK>>
  IssueId : uui <<FK>>
  DueDate : datetime
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

project ||..o{ issue
issueType ||..o{ issue
priority ||..o{ issue
profile ||..o{ issue
issue ||..o{ issue
issue ||..o{ issue
issue ||..o{ issue
projectWorkflowStatus ||..o{ issue
projectWorkflowResolvation ||..o{ issue
project ||..o{ projectWorkflow
projectWorkflow ||..o{ projectWorkflowStatus
projectWorkflowStatus ||..o{ projectWorkflowProgress
projectWorkflowStatus ||..o{ projectWorkflowProgress
issue ||..o{ issueComment
project ||..o{ projectMeeting
profile ||..o{ meetingInvitees
projectMeeting ||..o{ meetingInvitees
department ||..o{ meetingMinutes
projectMeeting ||..o{ meetingMinutes
issue ||..o{ issueAttachment
document ||..o{ issueAttachment
document ||..o{ projectMeeting
meetingType ||..o{ projectMeeting
projectWorkflow ||..o{ workflowEligibleFileExtension
issue ||..o{ workLog
timeUnit ||..o{ workLog
issue ||..o{  issueWorkflowHistory
status ||..o{ issueWorkflowHistory
status ||..o{ issueWorkflowHistory
projectWorkflowProgress ||..o{ issueWorkflowHistory
projectWorkflowResolvation ||..o{ issueWorkflowHistory
project ||..o{ release
release ||..o{ releaseIssue
issue ||..o{ releaseIssue
project ||..o{ projectProfileMember
profile ||..o{ projectProfileMember
project ||..o{ projectGroupMember
groups ||..o{ projectGroupMember
project ||..o{ projectRoleMember
role ||..o{ projectRoleMember
project ||..o{ projectDepartmentMember
department ||..o{ projectDepartmentMember
projectWorkflow ||..o{ projectWorkflowDocumentType
projectWorkflow ||..o{ projectWorkflowResolvation
resolvation ||..o{ projectWorkflowResolvation
@enduml