@startuml
hide circle
skinparam classBackgroundColor #Business
skinparam linetype ortho
skinparam Shadowing True
skinparam TitleFontSize 72pt

title Horizon Research Project (HRP) \n Overall Entity Relationship Diagram \n Version 26.5.18

entity "Basic.ContractType" as contractType #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.EducationLevel" as educationLevel #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.DocumentType" as documentType #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.FileExtension" as fileExtension #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.Priority" as priority #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *Ordering : integer
  *Color : varchar(7)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.IssueType" as issueType #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *IconAddress : varchar(1000)
  *Color : varchar(7)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.Status" as status #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *Color : varchar(7)
  *StatusEffect : enum(ToDo, InProgress, Done)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.Resolvation" as resolvation #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *Color : varchar(7)
  *IsResolved : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.MeetingType" as meetingType #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.TimeUnit" as timeUnit #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  BasedOnMillisecond : bigint(19)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.TestApproval" as testApproval #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *IsApproved : boolean
  *Color : varchar(10)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.TestComplexityLevel" as testComplexityLevel #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *ValueNumber : float
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Basic.Currency" as currency #LightPink{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *Symbol : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Role" as role #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Groups" as groups #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Permission" as permission #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Form" as form #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.FormPermission" as formPermission #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *FormId : uuid <<FK>>
  *PermissionId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.RolePermission" as rolePermission #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *RoleId : uuid <<FK>>
  *FormPermissionId : uuid <<FK>>
  *ActiveFrom : datetime
  ActiveTo : datetime
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.GroupPermission" as groupPermission #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *GroupId : uuid <<FK>>
  *FormPermissionId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.ProfilePermission" as profilePermission #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *PermissionId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Profile" as profile #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *FirstName : varchar(200)
  *LastName : varchar(200)
  *Gender : enum(male, female)
  *StaffNumber : varchar(20) <<unique>>
  *ActiveFrom : timestamp
  ActiveTo : timestamp
  PositionId : uuid <<FK>>
  Avatar : text
  Birthday : date
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  EmailAddress : varchar(200)
  Address : varchar(1000)
  PostalCode : varchar(20)
  LastLogInDate : timestamp
  LogInCount : integer(10) <<default: 0>>
  WrongLogInCount : integer(10) <<default: 0>>
  *Username : varchar(200) <<unique>>
  *Pass : varchar(255)
  PassSalt : varchar(50)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.ProfileRole" as profileRole #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *RoleId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.ProfileGroup" as profileGroup #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *GroupId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.Document" as document #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TableName : varchar(255)
  *TableId : bigint(19)
  *DocumentTypeId : uuid <<FK>>
  *FileExtensionId : uuid <<FK>>
  *FileAddress: varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.ProjectWorkflowDocumentType" as projectWorkflowDocumentType #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *DocumentTypeId : uuid <<FK>> <<composite unique>>
  *ProjectWorkflowId : uuid <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.WorkflowEligibleFileExtension" as workflowEligibleFileExtension #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *WorkflowId : uuid <<FK>> <<composite unique>>
  *FileExtensionId : uuid <<FK>> <<composite unique>>
  *MaxFileSizeForUpload : integer <<default: 5242880>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Department" as department #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(50)
  *Code : varchar(20) <<unique>>
  ParentId : integer(20) <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Position" as position #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(50)
  *Code : varchar(20) <<unique>>
  *DepartmentId : uuid <<FK>>
  ParentId : uuid <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.ProfileEducation" as profileEducation #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *EducatioLevelId : uuid <<FK>>
  DocumentId : uuid <<FK>>
  *Title : varchar(255)
  CollegeName : varchar(255)
  StartDate : date
  EndDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.ProfileJobExperience" as profileJobExperience #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *JobTitle : varchar(200)
  *CompanyName : varchar(200)
  StartDate : date
  EndDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.ProfileCertificate" as profileCertificate #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *Title : varchar(200)
  *InstituteName : varchar(200)
  StartDate : date
  EndDate : date
  HasCertificate : boolean
  DocumentId : uuid <<FK>>
  CertificateFileAddress : varchar(4000)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.WorkingTimeTable" as workingTimeTable #Lavender{ 
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *WorkingDay : enum(Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday)
  *ContractTypeId : uuid <<FK>>
  *Title : varchar(200)
  *StartTime : time
  *EndTime : time
  FloatingStartTime : time
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Holidaies" as holidaies #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(255)
  *HolidayDate : date <<unique>> 
  *HolidayType : enum(National, GovernmentOrFederal, ProvincialOrState, Organizational)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Attendance" as attendance #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *WorkingDate : date
  *EnteranceType : enum(enter, exit)
  *EnternaceTime : time
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Leave" as leave #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  LeaveType : enum(fulltime, parttime)
  *LeavingStartDate : date
  LeavingEndDate : date
  *LeavingStartTime : time
  *LeavingEndTime : time
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.WorkMission" as workMission #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *MissionStartDate : date
  MissionEndDate : date
  *MissionStartTime : time
  *MissionEndTime : time
  MissionLocation : varchar(255)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Project" as project #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  StartDate : date
  EndDate : date
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectProfileMember" as projectProfileMember #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>> <<composite unique>>
  *ProfileId : uuid <<FK>> <<composite unique>>
  *IsProjectManager : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectGroupMember" as projectGroupMember #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>> <<composite unique>>
  *GroupId : uuid <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectRoleMember" as projectRoleMember #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>> <<composite unique>>
  *RoleId : uuid <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectDepartmentMember" as projectDepartmentMember #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>> <<composite unique>>
  *DepartmentId : uuid <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflow" as projectWorkflow #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflowStatus" as projectWorkflowStatus #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectWorkflowId : uuid <<FK>>
  *StatusId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflowResolvation" as projectWorkflowResolvation #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectWorkflowId : uuid <<FK>>
  *ResolvationId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflowProgress" as projectWorkflowProgress #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(255)
  StartProjectWorkflowStatusId : uuid <<FK>>
  *IsFromStartPoint : boolean
  *CanBeStartedFromAnyStatus : boolean
  EndProjectWorkflowStatusId : uuid <<FK>>
  *IsWorkflowEndPoint : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Issue" as issue #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>>
  AssigneeId : uuid <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  DueDate : date
  PriorityId : uuid <<FK>>
  *IssueTypeId : uuid <<FK>>
  IssueSize : enum(XS, S, M , L , XL)
  ParentIssueId : uuid <<FK>>
	EpicLinkedId : uuid <<FK>>
	LinkedIssueId : uuid <<FK>>
	LinkedIssueType : enum(Blocks, RelatesTo, Duplicates, Clones)
  *CurrentStatusId : uuid <<FK>>
  *CurrentResolvationId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.IssueComment" as issueComment #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *IssueId : uuid <<FK>>
  *CommentText : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.IssueAttachment" as issueAttachment #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *IssueId : uuid <<FK>> <<composite unique>>
  *DocumentId : uuid <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectRelease" as release #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>>
  *VersionNumber : varchar(20) <<unique>>
  ReleaseDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectReleaseIssue" as releaseIssue #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectReleaseId : uuid <<FK>> <<composite unique>>
  *IssueId : uuid <<FK>> <<composite unique>>
  IsFinalized : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.WorkLog" as workLog #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *IssueId : uuid <<FK>>
  *LogDate : date
  *StartWorkTime : time
  *WorkingDuration : float 
  *TimeUnitId : uuid <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.WorkflowEligibleFileExtension" as workflowEligibleFileExtension #Gold{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *WorkflowId : uuid <<FK>> <<composite unique>>
  *FileExtensionId : uuid <<FK>> <<composite unique>>
  *MaxFileSizeForUpload : integer <<default: 5242880>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.IssueWorkflowHistory" as issueWorkflowHistory #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *IssueId : uuid <<FK>>
  *StartStatusId : uuid <<FK>>
  *EndStatusId : uuid <<FK>>
  *ProjectWorkflowProgressId : uuid <<FK>>
  ProjectWorkflowResolvationId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectMeeting" as projectMeeting #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>>
  *MeetingTypeId : uuid <<FK>>
  *MeetingDate : date
  *Title : varchar(255)
  *Location : varchar(255)
  MinutesDocumentId : uuid <<FK>>
  Description : varchar(4000)
  ScheduleStartTime : time
  ScheduleEndTime : time
  ActualStartTime : time
  ActualEndTime : time
  *IsCanncelled : boolean <<default: false>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.MeetingInvitees" as meetingInvitees #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectMeetingId : uuid <<FK>>
  *IsFromInsideCompnay : boolean
  ProfileId : uuid <<FK>>
  InviteeFullName : varchar(255)
	InviteeCompanyName : varchar(255)
  IsAttanded : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.MeetingMinutes" as meetingMinutes #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectMeetingId : uuid <<FK>>
  *Resolution : varchar(4000)
  ResponsibleDepartmentId : uuid <<FK>>
  IssueId : uuid <<FK>>
  DueDate : datetime
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.StaffContract" as staffContract #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *ContractTypeId : uuid <<FK>>
  *StartDate : date
  *EndDate : date
  *Title : varchar(200)
  Description : varchar(4000)
  AutoRenewal : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractSalaryItem" as contractSalaryItem #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *StaffContractId : uuid <<FK>>
  *Title : varchar(200)
  *Amount : numeric(22,2)
  *CurrencyId : uuid <<FK>>
  Description : varchar(4000)
  *CalculationTimeUnitId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractDeductionItem" as contractDeductionItem #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *StaffContractId : uuid <<FK>>
  *Title : varchar(200)
  *CalculationType : enum(percentage, fixedAmount)
  DeductionPercentage : numeric(3,2) <<from 0 until 100>>
  FixedAmount : numeric(22,2)
  FixedAmountCurrencyId : uuid <<FK>>
  Description : varchar(4000)
  *CalculationTimeUnitId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.Supplier" as supplier #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(255)
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  FaxNumber : varchar(20)
  Email : varchar(100)
  PostalCode : varchar(20)
  City : varchar(255)
  Address : varchar(4000)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.CostInvoice" as costInvoice #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *SupplierId : uuid <<FK>>
  *DocumentId : uuid <<FK>>
  *InvoiceDate : date
  *TotalAmount : numeric(22,2)
  *CurrencyId : uuid <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.CostInvoiceItem" as costInvoiceItem #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CostInvoiceId : uuid <<FK>>
  *ItemTitle : varchar(255)
  *UnitAmount : numeric(22,2)
  *CurrencyId : uuid <<FK>>
  *Quantity : float
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ProjectDirectCostItem" as projectDirectCostItem #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>>
  *CostInvoiceItemId : uuid <<FK>>
  *AllocatedQuantity : float
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.CostPaymentReceipt" as costPaymentReceipt #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CostInvoiceId : uuid <<FK>>
  *ReceiptNumber : varchar(20)
  *DocumentId : uuid <<FK>>
  *Amount : numeric(22,2)
  *CurrencyId : uuid <<FK>>
  *PaymentDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.SalaryPaymentReceipt" as salaryPaymentReceipt #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *StaffContractId : uuid <<FK>>
  *ReceiptNumber : varchar(20)
  *DocumentId : uuid <<FK>>
  *Amount : numeric(22,2)
  *CurrencyId : uuid <<FK>>
  *PaymentDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.StaffAdditionalPaymentReceipt" as staffAdditionalPaymentReceipt #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *Title : varchar(255)
  *DocumentId : uuid <<FK>>
  *Amount : numeric(22,2)
  *CurrencyId : uuid <<FK>>
  *PaymentDate : date
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.Customer" as customer #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(255)
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  Email : varchar(100)
  PostalCode : varchar(20)
  Address : varchar(4000)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.Contract" as contract #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CustomerId : uuid <<FK>>
  *ProjectId : uuid <<FK>>
  *ContractNumber : varchar(20)
  StartDate : date
  ScheduledEndDate : date
  RealEndDate : date
  IsDevelopmentContract : boolean
  IsSupportContract : boolean
  *TotalAmount : numeric(22,2)
  *CurrencyId : uuid <<FK>>
  DocumentId : uuid <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractPaymentSchedule" as contractPaymentSchedule #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ContractId : uuid <<FK>>
  *PaymentTitle : varchar(255)
  ProjectReleaseId : uuid <<FK>>
  ScheduledPaymentDate : date
  *Amount : numeric(22,2)
  *CurrencyId : uuid <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractPaymentReceipt" as contractPaymentReceipt #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ContractPaymentScheduleId : uuid <<FK>>
  *ReceiptNumber : varchar(20)
  *PaymentDate : date
  DocumentId : uuid <<FK>>
  *Amount : numeric(22,2)
  *CurrencyId : uuid <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestScenario" as testScenario #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(255)
  TestComplexityLevelId : uuid <<FK>>
  UsersAndRoles : varchar(4000)
  Steps : varchar(4000)
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.PrerequisiteTestScenario" as prerequisiteTestScenario #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TestScenarioId : uuid <<FK>>
  *PrerequisiteTestScenarioId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestPlan" as testPlan #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Code : varchar(20) <<unique>>
  *Title : varchar(255)
  PlanningDate : date
  ProjectReleaseId : uuid <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestPlanScenario" as testPlanScenario #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TestScenarioId : uuid <<FK>> <<composite unique>>
  *TestPlanId : uuid <<FK>> <<composite unique>>
  *Ordering : float <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestPlanScenarioIssueCoverage" as testPlanScenarioIssueCoverage #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TestPlanScenarioId : uuid <<FK>> <<composite unique>>
  *IssueId : uuid <<FK>> <<composite unique>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestResult" as testResult #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *TestDate : date
  *TestPlanId : uuid <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "QualityControl.TestResultDetail" as testResultDetail #Silver{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  TestPlanScenarioId : uuid <<FK>>
  *TestApprovalId : uuid <<FK>>
  *Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Profile" as profile #Violet{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *FirstName : varchar(200)
  *LastName : varchar(200)
  *Gender : enum(male, female)
  *StaffNumber : varchar(20) <<unique>>
  *ActiveFrom : timestamp
  ActiveTo : timestamp
  PositionId : uuid <<FK>>
  Avatar : text
  Birthday : date
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  EmailAddress : varchar(200)
  Address : varchar(1000)
  PostalCode : varchar(20)
  LastLogInDate : timestamp
  LogInCount : integer(10) <<default: 0>>
  WrongLogInCount : integer(10) <<default: 0>>
  *Username : varchar(200) <<unique>>
  *Pass : varchar(255)
  PassSalt : varchar(50)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Department" as department #Lavender{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(50)
  *Code : varchar(20) <<unique>>
  ParentId : integer(20) <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Project" as project #Orange{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  StartDate : date
  EndDate : date
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Finance.Customer" as customer #Salmon{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(255)
  Description : varchar(4000)
  Address : varchar(4000)
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  Email : varchar(100)
  PostalCode : varchar(20)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.Question" as question #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireId : uuid <<FK>>
  *Question : varchar(4000)
  *Code : varchar(20) <<unique>>
  *AnswerType : enum(SingleChoice, MultiChoice, Description)
  *Score : integer
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionOption" as questionOption #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionId : uuid <<FK>>
  *Title : varchar(4000)
  *Score : integer
  *IsDescriptionRequired : boolean
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.Questionnaire" as questionnaire #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  ProjectId : uuid <<FK>>
  *QuestionnaireAduience : enum(Staffs, Customers, SeniorManagers, Stackholders)
  *TotalScore : integer
  *AcceptableScore : integer
  *WarningScore : integer
  *DisasterScore : integer
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionnaireTargetDepartment" as questionnaireTargetDepartment #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireId : uuid <<FK>>
  *DepoartmentId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionnaireItem" as questionnaireItem #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireId : uuid <<FK>>
  *QuestionId : uuid <<FK>>
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionnaireResult" as questionnaireResult #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireId : uuid <<FK>>
  ProfileId : uuid <<FK>>
  CustomerId : uuid <<FK>>
  *TotalScore : integer
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.QuestionnaireResultDetail" as questionnaireResultDetail #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *QuestionnaireResultId : uuid <<FK>>
  *QuestionnaireItemId : uuid <<FK>>
  ChoosedQuestionOptionId : uuid <<FK>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.CustomerFeedback" as customerFeedback #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CustomerId : uuid <<FK>>
  *ProjectId : uuid <<FK>>
  *FeedbackDate : date
  *FeedbackValue : numeric(2,2) <<between 1 and 10>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.StaffSatisfactionEvaluation" as staffSatisfactionEvaluation #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProfileId : uuid <<FK>>
  *EvalationDate : date
  *EvaluatedValue : numeric(3,2) <<between 1 and 100>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.ProjectProductivityEvaluation" as projectProductivityEvaluation #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *ProjectId : uuid <<FK>>
  *EvalationDate : datetime
  *EvaluatedValue : numeric(3,2) <<between 1 and 100>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

entity "Evaluation.CustomerSatisfactionEvaluation" as customerSatisfactionEvaluation #SkyBlue{
  *Id : uuid <<PK>> <<default: gen_random_uuid()>>
  --
  *CustomerId : uuid <<FK>>
  *ProjectId : uuid <<FK>>
  *EvalationDate : datetime
  *EvaluatedValue : numeric(3,2) <<between 1 and 100>>
  Description : varchar(4000)
  *ActiveStaus : enum(Active, Inactive, Deleted) <<default: Active>>
  *CreateDate : timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate : timestamp
  ModifierId : bigint(19)
}

form ||..o{ formPermission
permission ||..o{ formPermission
role ||..o{ rolePermission
permission ||..o{ rolePermission
groups ||..o{ groupPermission
permission ||..o{ groupPermission
profile ||..o{ profilePermission
permission ||..o{ profilePermission
profile ||..o{ profileRole
role ||..o{ profileRole
profile ||..o{ profileGroup
groups ||..o{ profileGroup
position ||..o{ profile

documentType ||..o{ document
fileExtension ||..o{ document

department |o..o{ department
position |o..o{ position
department ||..o{ position
position ||..o{ profile
profile ||..o{ profileEducation
educationLevel ||..o{ profileEducation
profile ||..o{ profileCertificate
profile ||..o{ profileJobExperience
profile ||..o{ attendance
profile ||..o{ leave
profile ||..o{ workMission
document ||..o{ profileEducation
document ||..o{ profileCertificate
contractType ||..o{ workingTimeTable

project ||..o{ issue
issueType ||..o{ issue
priority ||..o{ issue
profile ||..o{ issue
issue ||..o{ issue
issue ||..o{ issue
issue ||..o{ issue
projectWorkflowStatus ||..o{ issue
projectWorkflowResolvation ||..o{ issue
project ||..o{ projectWorkflow
projectWorkflow ||..o{ projectWorkflowStatus
projectWorkflowStatus ||..o{ projectWorkflowProgress
projectWorkflowStatus ||..o{ projectWorkflowProgress
issue ||..o{ issueComment
project ||..o{ projectMeeting
profile ||..o{ meetingInvitees
projectMeeting ||..o{ meetingInvitees
department ||..o{ meetingMinutes
projectMeeting ||..o{ meetingMinutes
issue ||..o{ issueAttachment
document ||..o{ issueAttachment
document ||..o{ projectMeeting
meetingType ||..o{ projectMeeting
projectWorkflow ||..o{ workflowEligibleFileExtension
issue ||..o{ workLog
timeUnit ||..o{ workLog
issue ||..o{  issueWorkflowHistory
status ||..o{ issueWorkflowHistory
status ||..o{ issueWorkflowHistory
projectWorkflowProgress ||..o{ issueWorkflowHistory
projectWorkflowResolvation ||..o{ issueWorkflowHistory
project ||..o{ release
release ||..o{ releaseIssue
issue ||..o{ releaseIssue
project ||..o{ projectProfileMember
profile ||..o{ projectProfileMember
project ||..o{ projectGroupMember
groups ||..o{ projectGroupMember
project ||..o{ projectRoleMember
role ||..o{ projectRoleMember
project ||..o{ projectDepartmentMember
department ||..o{ projectDepartmentMember
projectWorkflow ||..o{ projectWorkflowDocumentType
projectWorkflow ||..o{ projectWorkflowResolvation
resolvation ||..o{ projectWorkflowResolvation

contractType ||..o{ staffContract
profile ||..o{ staffContract
staffContract ||..o{ contractSalaryItem
timeUnit ||..o{ contractSalaryItem
currency ||..o{ contractSalaryItem
supplier ||..o{ costInvoice
document ||..o{ costInvoice
currency ||..o{ costInvoice
costInvoice ||..o{ costInvoiceItem
currency ||..o{ costInvoiceItem
costInvoiceItem ||..o{ projectDirectCostItem
project ||..o{ projectDirectCostItem
costInvoiceItem ||..o{ projectDirectCostItem
costInvoice ||..o{ costPaymentReceipt
document ||..o{ costPaymentReceipt
currency ||..o{ costPaymentReceipt
staffContract ||..o{ contractDeductionItem
timeUnit ||..o{ contractDeductionItem
currency ||..o{ contractDeductionItem
document ||..o{ salaryPaymentReceipt
staffContract ||..o{ salaryPaymentReceipt
currency ||..o{ salaryPaymentReceipt
profile ||..o{ staffAdditionalPaymentReceipt
document ||..o{ staffAdditionalPaymentReceipt
contract ||..o{ contractPaymentSchedule
currency ||..o{ contractPaymentSchedule
release ||..o{ contractPaymentSchedule
contractPaymentSchedule ||..o{ contractPaymentReceipt
currency ||..o{ contractPaymentReceipt
document ||..o{ contractPaymentReceipt
customer ||..o{ contract
project ||..o{ contract
currency ||..o{ contract
document |o..o{ contract

project ||..o{ testScenario
testComplexityLevel |o..o{ testScenario
testScenario ||..o{ prerequisiteTestScenario
testScenario ||..o{ prerequisiteTestScenario
testScenario ||..o{ prerequisiteTestScenario
release |o..o{ testPlan
testScenario ||..o{ testPlanScenario
testPlan ||..o{ testPlanScenario
testPlanScenario ||..o{ testPlanScenarioIssueCoverage
issue ||..o{ testPlanScenarioIssueCoverage
testPlan ||..o{ testResult
testPlanScenario |o..o{ testResultDetail
testApproval ||..o{ testResultDetail

questionnaire ||..o{ questionnaireTargetDepartment
department ||..o{ questionnaireTargetDepartment
question ||..o{ questionnaireItem
project ||..o{ questionnaire
questionnaire ||..o{ questionnaireItem
question ||..o{ questionOption
questionnaire ||..o{ questionnaireResult
profile |o..o{ questionnaireResult
customer |o..o{ questionnaireResult
questionnaireResult ||..o{ questionnaireResultDetail
questionnaireItem ||..o{ questionnaireResultDetail
questionOption |o..o{ questionnaireResultDetail
profile ||..o{ staffSatisfactionEvaluation
project ||..o{ projectProductivityEvaluation
customer ||..o{ customerSatisfactionEvaluation
project ||..o{ customerSatisfactionEvaluation
customer ||..o{ customerFeedback
project ||..o{ customerFeedback